#!/usr/bin/env python3
"""
run_demo.py – ThermoTrace Temporal Intelligence Engine Demo

Runs all four synthetic scenarios and prints concise, readable results.

IMPORTANT: These scenarios use SYNTHETIC data created for functional
testing of the engine. The outputs are generated by the implemented
algorithms, not hard-coded. They must NOT be presented as real-world
observations or validated accuracy claims.

Usage:
    python scripts/run_demo.py
"""

from __future__ import annotations

import json
import logging
import sys
from datetime import datetime
from pathlib import Path

# Add src/ to path so the package is importable without install
sys.path.insert(0, str(Path(__file__).parent.parent / "src"))

from thermotrace_temporal.pipeline import analyze_event

# Configure concise logging for demo
logging.basicConfig(
    level=logging.WARNING,
    format="%(levelname)s | %(name)s | %(message)s",
)


EXAMPLES_DIR = Path(__file__).parent.parent / "examples"

DIVIDER = "=" * 65


def load_scenario(filename: str) -> list[dict]:
    """Load a JSON scenario file."""
    path = EXAMPLES_DIR / filename
    with path.open("r", encoding="utf-8") as f:
        return json.load(f)


def make_historical(observations: list[dict], frp_mean: float, count: int) -> list[dict]:
    """
    Generate minimal synthetic historical observations for baseline.
    Uses the first observation's location/facility as template.
    This is synthetic test data only.
    """
    if not observations:
        return []
    template = observations[0].copy()
    hist = []
    base_dt = datetime(2025, 10, 1, 8, 0, 0)
    for i in range(count):
        import random
        obs = template.copy()
        obs["observation_id"] = f"HIST-SYNTH-{i:04d}"
        obs["timestamp_utc"] = (base_dt.replace(day=1 + (i % 28))).isoformat() + "Z"
        obs["frp"] = round(frp_mean + random.uniform(-5, 5), 1)
        hist.append(obs)
    return hist


def print_result(scenario_name: str, result: dict) -> None:
    """Print a concise summary of a pipeline result."""
    anomaly = result.get("anomaly", {})
    il = result.get("industrial_likelihood", {})
    risk = result.get("operational_risk", {})
    alert = result.get("alert", {})
    evidence = result.get("evidence", {})
    recommendation = result.get("recommendation", "N/A")
    facility = result.get("facility", {})
    baseline = result.get("baseline", {})
    tw30 = result.get("temporal_features", {}).get("window_30d", {})

    print(f"\n{DIVIDER}")
    print(f"SCENARIO: {scenario_name}")
    print(DIVIDER)
    print(f"  Event ID:              {result.get('event_id', 'N/A')}")
    print(f"  Facility:              {facility.get('facility_id', 'None')} ({facility.get('facility_type', 'N/A')})")
    print(f"  Facility distance:     {facility.get('distance_km', 'N/A')} km")
    print()
    print(f"  — Current Activity —")
    print(f"  Detections (30d):      {tw30.get('detection_count', 0)}")
    print(f"  Active days (30d):     {tw30.get('active_days', 0)}")
    print(f"  Persistence ratio:     {tw30.get('persistence_ratio', 'N/A')}")
    print(f"  FRP mean (30d):        {tw30.get('frp_mean', 'N/A')} MW")
    print(f"  FRP max (30d):         {tw30.get('frp_max', 'N/A')} MW")
    print(f"  Spatial stability:     {tw30.get('spatial_stability_score', 'N/A')}/100")
    print()
    print(f"  — Baseline —")
    print(f"  Available:             {baseline.get('available', False)}")
    print(f"  Baseline FRP mean:     {baseline.get('frp_mean', 'N/A')} MW")
    print(f"  Baseline quality:      {baseline.get('history_quality', 'N/A')}")
    print()
    print(f"  — Scores —")
    print(f"  Anomaly score:         {anomaly.get('score', 'N/A')} / 100")
    print(f"  Anomaly level:         {anomaly.get('level', 'N/A').upper()}")
    print(f"  Industrial likelihood: {il.get('score', 'N/A')} / 100")
    print(f"  Requires verification: {il.get('requires_verification', 'N/A')}")
    print(f"  Risk score:            {risk.get('risk_score', 'N/A')} / 100")
    print(f"  Risk level:            {risk.get('risk_level', 'N/A').upper()}")
    print(f"  Risk confidence:       {risk.get('score_confidence', 'N/A')}")
    print()
    print(f"  — Alert —")
    print(f"  Type:                  {alert.get('alert_type', 'N/A')}")
    print(f"  Priority:              {alert.get('priority', 'N/A')}")
    print()
    print(f"  — Anomaly Reasons —")
    for r in anomaly.get("reasons", []):
        print(f"    - {r}")
    print()
    print(f"  — Evidence For —")
    for e in evidence.get("evidence_for", [])[:4]:
        print(f"    + {e}")
    print()
    print(f"  — Evidence Against —")
    for e in evidence.get("evidence_against", [])[:3]:
        print(f"    - {e}")
    print()
    print(f"  — Missing Evidence —")
    for e in evidence.get("missing_evidence", [])[:3]:
        print(f"    ? {e}")
    print()
    print(f"  — Recommendation —")
    print(f"    {recommendation}")


def main() -> None:
    print("\nThermoTrace Temporal Intelligence Engine — Demo")
    print("NOTE: All data is SYNTHETIC and for functional testing only.")
    print("Outputs are generated by the algorithms, not hard-coded.\n")

    # ------------------------------------------------------------------
    # SCENARIO 1: Persistent Industrial Source
    # ------------------------------------------------------------------
    obs1 = load_scenario("persistent_industrial.json")
    hist1 = make_historical(obs1, frp_mean=41.0, count=45)  # good historical baseline
    result1 = analyze_event(
        observations=obs1,
        historical_observations=hist1,
        current_period_start=datetime(2026, 1, 10),
    )
    print_result("Persistent Industrial Source", result1)

    # ------------------------------------------------------------------
    # SCENARIO 2: Abnormal Industrial Event
    # ------------------------------------------------------------------
    obs2 = load_scenario("abnormal_industrial.json")
    # Historical baseline: normal activity at ~46 MW
    hist2 = make_historical(obs2[:2], frp_mean=46.0, count=40)
    result2 = analyze_event(
        observations=obs2,
        historical_observations=hist2,
        current_period_start=datetime(2026, 1, 13),
    )
    print_result("Abnormal Industrial Event", result2)

    # ------------------------------------------------------------------
    # SCENARIO 3: Natural/Forest Fire
    # ------------------------------------------------------------------
    obs3 = load_scenario("natural_fire.json")
    result3 = analyze_event(
        observations=obs3,
        historical_observations=[],  # no historical data for this location
        current_period_start=datetime(2026, 1, 13),
    )
    print_result("Natural/Forest Fire", result3)

    # ------------------------------------------------------------------
    # SCENARIO 4: Insufficient History
    # ------------------------------------------------------------------
    obs4 = load_scenario("insufficient_history.json")
    result4 = analyze_event(
        observations=obs4,
        historical_observations=[],  # explicitly no history
        current_period_start=datetime(2026, 1, 14),
    )
    print_result("Insufficient History", result4)

    print(f"\n{DIVIDER}")
    print("Demo complete. See docs/ for integration contracts.")
    print(f"{DIVIDER}\n")


if __name__ == "__main__":
    main()
