"""
Unit and QA Tests for ThermoTrace Population Module
===================================================

Tests:
- metadata validation
- NoData handling
- negative-value detection
- chunked statistics
- spatial bounds validation
- source immutability
- derived-raster equivalence
"""

import os
from pathlib import Path
import pytest
import numpy as np
import rasterio

PROJECT_ROOT = Path(__file__).resolve().parents[1]
RAW_PATH = PROJECT_ROOT / "data" / "raw" / "population" / "ind_pop_2025_CN_100m_R2025A_v1.tif"
if not RAW_PATH.exists():
    fallback = PROJECT_ROOT / "population" / "ind_pop_2025_CN_100m_R2025A_v1.tif"
    if fallback.exists():
        RAW_PATH = fallback

SAMPLE_PATH = PROJECT_ROOT / "data" / "processed" / "population" / "population_india_sample_100km.tif"

def test_source_immutability():
    """Verify raw file exists, has expected size, and is accessible in read-only mode."""
    assert RAW_PATH.exists(), f"Raw population file missing: {RAW_PATH}"
    size = RAW_PATH.stat().st_size
    assert size == 778106191, f"Raw population file size changed! Expected 778106191, got {size}"

def test_metadata_validation():
    """Verify CRS, dimensions, single-band, and datatype."""
    with rasterio.open(RAW_PATH) as src:
        assert src.crs.to_string() == "EPSG:4326"
        assert src.count == 1
        assert src.width == 35040
        assert src.height == 34507
        assert src.dtypes[0] == "float32"
        assert src.nodata == -99999.0

def test_spatial_bounds():
    """Verify bounds encompass Indian subcontinental extent."""
    with rasterio.open(RAW_PATH) as src:
        b = src.bounds
        assert b.left <= 68.2
        assert b.bottom <= 6.8
        assert b.right >= 97.3
        assert b.top >= 35.5

def test_nodata_and_negative_handling():
    """Verify that NoData (-99999.0) is correctly isolated and no invalid negative values exist."""
    with rasterio.open(RAW_PATH) as src:
        # Read a representative 512x512 block known to cross land and water/NoData
        window = rasterio.windows.Window(5000, 28000, 512, 512)
        block = src.read(1, window=window)
        nodata_val = src.nodata

        # Valid cells should have no negative values
        valid_cells = block[block != nodata_val]
        if valid_cells.size > 0:
            assert np.all(valid_cells >= 0.0), "Found negative population in valid cells!"
            assert not np.any(np.isnan(valid_cells)), "Found NaN in valid cells!"
            assert not np.any(np.isinf(valid_cells)), "Found Inf in valid cells!"

def test_chunked_statistics_consistency():
    """Verify that chunked block summation matches full array reading on a window."""
    with rasterio.open(RAW_PATH) as src:
        test_window = rasterio.windows.Window(10000, 10000, 1024, 1024)
        full_block = src.read(1, window=test_window)
        nodata_val = src.nodata

        valid_full = full_block[full_block != nodata_val]
        expected_sum = float(np.sum(valid_full))

        # Sum via 2 sub-windows
        w1 = rasterio.windows.Window(10000, 10000, 1024, 512)
        w2 = rasterio.windows.Window(10000, 10512, 1024, 512)
        b1 = src.read(1, window=w1)
        b2 = src.read(1, window=w2)
        v1 = b1[b1 != nodata_val]
        v2 = b2[b2 != nodata_val]
        chunked_sum = float(np.sum(v1)) + float(np.sum(v2))

        assert np.isclose(expected_sum, chunked_sum, rtol=1e-5)

def test_qa_sample_raster():
    """Verify that the QA sample raster exists and preserves source properties."""
    if not SAMPLE_PATH.exists():
        pytest.skip("Sample raster not yet generated by process_population.py")
    with rasterio.open(SAMPLE_PATH) as src:
        assert src.crs.to_string() == "EPSG:4326"
        assert src.width == 1000
        assert src.height == 1000
        assert src.nodata == -99999.0
        data = src.read(1)
        valid = data[data != src.nodata]
        assert valid.size > 0
        assert np.all(valid >= 0.0)
