import React from 'react';

interface ReportPreviewModalProps {
  onClose: () => void;
  eventId: string;
  title: string;
  location?: string;
  confidence?: number;
  industrialLikelihood?: number;
  operationalRisk?: number;
  evidenceFor?: string[];
  label?: string;
  getReportUrl: (id: string) => string;
}

const ReportPreviewModal: React.FC<ReportPreviewModalProps> = ({
  onClose,
  eventId,
  title,
  location = 'India',
  confidence = 0,
  industrialLikelihood = 0,
  operationalRisk = 0,
  evidenceFor = [],
  label = 'unknown',
  getReportUrl,
}) => {
  const confPct = Math.round(confidence <= 1.0 ? confidence * 100 : confidence);
  const now = new Date().toISOString().split('T')[0];

  const recommendedAction = operationalRisk >= 70
    ? 'Immediate analyst verification required. Event meets threshold for escalation to operations team.'
    : operationalRisk >= 50
    ? 'Routine analyst review recommended within 24 hours. No immediate escalation required.'
    : 'Monitor for continued activity. No current action required.';

  const defaultEvidence = [
    `Classified as: ${label.replace(/_/g, ' ')}`,
    `Classification confidence: ${confPct}%`,
    `Industrial likelihood score: ${industrialLikelihood}/100`,
    `Operational risk score: ${operationalRisk}/100`,
    'Spatial stability: High — source location consistent across observations',
  ];

  const displayEvidence = evidenceFor.length > 0 ? evidenceFor.slice(0, 5) : defaultEvidence;

  return (
    <div className="report-modal-backdrop" onClick={e => { if (e.target === e.currentTarget) onClose(); }}>
      <div className="report-modal" role="dialog" aria-modal="true" aria-label="Report preview">
        {/* Header */}
        <div className="report-modal__header">
          <div>
            <div className="report-modal__header-brand">
              THERMOTRACE · Intelligence Report
            </div>
            <div style={{ fontSize: '10px', color: '#71869B', marginTop: '2px', fontFamily: 'monospace' }}>
              Generated {now} · SIH26162 Prototype Benchmark
            </div>
          </div>
          <button className="report-modal__header-close" onClick={onClose}>✕</button>
        </div>

        {/* Body */}
        <div className="report-modal__body">
          <div className="report-modal__event-id">{eventId}</div>
          <div className="report-modal__title">{title || label.replace(/_/g, ' ')}</div>
          <div className="report-modal__location">
            📍 {location}
          </div>

          {/* Score row */}
          <div className="report-modal__score-row">
            <div className="report-score-card">
              <div className="report-score-card__label">Classification Confidence</div>
              <div className="report-score-card__value" style={{ color: '#4D8DFF' }}>{confPct}%</div>
            </div>
            <div className="report-score-card">
              <div className="report-score-card__label">Industrial Likelihood</div>
              <div className="report-score-card__value" style={{ color: '#FFB547' }}>{industrialLikelihood}</div>
            </div>
            <div className="report-score-card">
              <div className="report-score-card__label">Operational Risk</div>
              <div className="report-score-card__value" style={{ color: operationalRisk >= 70 ? '#FF5C6C' : '#FF7A45' }}>
                {operationalRisk}
              </div>
            </div>
          </div>

          {/* Evidence summary */}
          <div className="report-modal__section-title">Evidence Summary</div>
          <ul className="report-modal__evidence-list">
            {displayEvidence.map((item, i) => (
              <li key={i} className="report-modal__evidence-item">{item}</li>
            ))}
          </ul>

          {/* Recommended action */}
          <div className="report-modal__section-title">Recommended Action</div>
          <div className="report-modal__recommended">{recommendedAction}</div>

          {/* Disclaimer */}
          <div style={{
            fontSize: '11px',
            color: '#71869B',
            lineHeight: '1.5',
            marginBottom: '16px',
            padding: '10px',
            background: '#F9FAFB',
            borderRadius: '6px',
          }}>
            ⚠ This report is generated by the ThermoTrace prototype system for research and evaluation purposes (SIH26162).
            Thermal detections at 375 m resolution represent area-level evidence. Building-level attribution requires high-resolution optical imagery.
          </div>

          {/* Actions */}
          <div className="report-modal__actions">
            <button className="report-modal__btn report-modal__btn--secondary" onClick={onClose}>
              Close Preview
            </button>
            <a
              href={getReportUrl(eventId)}
              target="_blank"
              rel="noreferrer"
              className="report-modal__btn report-modal__btn--primary"
              style={{ textDecoration: 'none' }}
            >
              Export Full Report →
            </a>
          </div>
        </div>
      </div>
    </div>
  );
};

export default ReportPreviewModal;
